Extracted strings to strings.xml
qveex/rst-tur pull request #4
Opened 2023-12-02 04:54 UTC by MJJacobs01

Took 44 minutes

#2 All strings from the screens and viewmodels extracted to strings.xml

2023-12-02 19:39 UTC, qveex requested changes
Good job!
But there are a few critical mistakes that need to be fixed
- using empty string res to replace `""` literal
- providing `application` context to `ViewModel`
- changing `ViewModel` to `AndroidViewModel` in `HomeViewModel`
- `navigation/Screen` class was not localized
- naming and grouping (but it is not critical)

2023-12-02 19:39 UTC, qveex commented on app/src/main/java/ru/qveex/rst_tur/presentation/components/BottomNav.kt
> +                contentDescription = stringResource(R.string.navigation_icon_content_description)
```suggestion
                contentDescription = screen.title
```
In this case you can use title of screen in bottom nav
But in `navigation
/Screen.kt` strings still not localized

2023-12-02 19:39 UTC, qveex commented on app/src/main/java/ru/qveex/rst_tur/presentation/components/lists/FoodList.kt
> +                text = stringResource(R.string.show_all_food_items, foods.size),
```suggestion
                text = stringResource(R.string.show_all, foods.size),
```
You can rename this string res
Because we can reuse this string in any other cases to show all items of any list

2023-12-02 19:39 UTC, qveex commented on app/src/main/java/ru/qveex/rst_tur/presentation/screens/blog/BlogScreen.kt
> +                    text = blogViewModel.blog?.date?.dateConvert() ?: stringResource(R.string.emptyString),
```suggestion
                    text = blogViewModel.blog?.date?.dateConvert() ?: "",
```

I think string res in these cases is redundant, because an empty string will always be empty  ¯\_(ツ)_/¯
And `""` can use string pull and don't waste time and memory to getting android resources

2023-12-02 19:39 UTC, qveex commented on app/src/main/java/ru/qveex/rst_tur/presentation/screens/home/HomeViewModel.kt
> +) : AndroidViewModel(application) {
Using `AndroidViewModel` is really bad practice as is getting `application` and it's `context` in `viewModel's` classes
[AndroidViewModel Problematic for unit tests](https://stackoverflow.com/questions/44148966/androidviewmodel-vs-viewmodel#:~:text=AndroidViewModel%20Problematic%20for%20unit%20tests)

If you want get android resources in VM - you can create `ResourceProvider` (I usually use this solution) and inject it into vm

2023-12-02 19:39 UTC, qveex commented on app/src/main/java/ru/qveex/rst_tur/presentation/screens/home/HomeViewModel.kt
> +                    AppStatus.Success(application.applicationContext.getString(R.string.emptyString))
redundant empty string res as before

2023-12-02 19:39 UTC, qveex commented on app/src/main/res/values/strings.xml
> +    <string name="room_photo_content_description">Room photo</string>
This string file is for Russian localization.

2023-12-02 19:39 UTC, qveex commented on app/src/main/res/values/strings.xml
> +    <string name="room_photo_content_description">Room photo</string>
I understand that these content descriptions were in eng lang in my code, but if you start localizing strings it must be localizied too

2023-12-02 19:39 UTC, qveex commented on app/src/main/res/values/strings.xml
> +    <string name="blog_fun_photo_content_description">Blog fun photo</string>
You can group strings by their usage

For example
```
<string name="title_for_children">Для детей</string>
<string name="title_hotels">Отели</string>
<string name="title_tours">Туры</string>

<string name="description_navigation_icon_content">Navigation Icon</string>
<string name="description_icon_content">icon</string>
<string name="description_back_icon_content">Back icon</string>
```

etc.

2023-12-02 19:39 UTC, qveex commented on app/src/main/res/values/strings.xml
> +    <string name="picked_image_content_description">Picked Image</string>
And also I have some questions to naming of strings

2023-12-02 19:39 UTC, qveex commented on app/src/main/res/values/strings.xml
> +    <string name="picked_image_content_description">Picked Image</string>
I think that the `description` and similar tags should be at the start of the name.
```suggestion
    <string name="description_picked_image_content">Picked Image</string>
```

2023-12-02 19:39 UTC, qveex commented on app/src/main/res/values/strings.xml
> +    <string name="tours">Туры</string>
And also in some strings you don't have any tags
But we know that this string, for example, use only for titles
```suggestion
    <string name="title_tours">Туры</string>
```

2023-12-02 19:39 UTC, qveex commented on app/src/main/res/values/strings.xml
> +    <string name="tours">Туры</string>
I'm not really sure that it should actually be like this, but that's how I usually do it

2023-12-24 14:16 UTC, qveex commented
@MJJacobs01 
Sry, I can't accept this PR 🤷‍♂️

2023-12-25 05:13 UTC, MJJacobs01 commented
Good morning,

I will fix all the suggestions by next weekend if you can wait until then.

Otherwise I will submit a new PR once done.

On Sun, 24 Dec 2023, 16:16 qveex, ***@***.***> wrote:

> @MJJacobs01 <https://github.com/MJJacobs01>
> Sry, I can't accept this PR 🤷‍♂️
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/qveex/rst-tur/pull/4#issuecomment-1868526912>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMNSYEHDXVWWNOS3BLXTWH3YLA2LRAVCNFSM6AAAAABADXV2QCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNRYGUZDMOJRGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-12-30 07:31 UTC, MJJacobs01 commented
Good morning,

I have made the required changes.

Please see if it is acceptable now?

2024-01-15 16:06 UTC, closed without merging